//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuMenuPedido.Domain.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensValidacaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensValidacaoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeuMenuPedido.Domain.Validations.MensagensValidacaoResources", typeof(MensagensValidacaoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se informar ao menos um produto no pedido.
        /// </summary>
        public static string DeveInformarProdutoNoPedido {
            get {
                return ResourceManager.GetString("DeveInformarProdutoNoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se informar a situação para o pedido.
        /// </summary>
        public static string DeveInformarSituacaoPedido {
            get {
                return ResourceManager.GetString("DeveInformarSituacaoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se obrigatoriamente informar o pedido.
        /// </summary>
        public static string IdentificadorDoPedidoObrigatorio {
            get {
                return ResourceManager.GetString("IdentificadorDoPedidoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mesa informada não foi identificada.
        /// </summary>
        public static string MesaNaoIdentificada {
            get {
                return ResourceManager.GetString("MesaNaoIdentificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se obrigatoriamente informar a mesa.
        /// </summary>
        public static string MesaObrigatoria {
            get {
                return ResourceManager.GetString("MesaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mesa já está ocupada.
        /// </summary>
        public static string MesaOcupada {
            get {
                return ResourceManager.GetString("MesaOcupada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível identificar o pedido.
        /// </summary>
        public static string PedidoNaoEncontrado {
            get {
                return ResourceManager.GetString("PedidoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar a situação de pedido que está pago ou cancelado.
        /// </summary>
        public static string PedidoPagoOuCanceladoNaoPodeMudarSituacao {
            get {
                return ResourceManager.GetString("PedidoPagoOuCanceladoNaoPodeMudarSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto informado não foi localizado no serviço de produtos, favor verificar e tentar novamente.
        /// </summary>
        public static string ProdutoNaoLocalizado {
            get {
                return ResourceManager.GetString("ProdutoNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se obrigatoriamente informar o produto.
        /// </summary>
        public static string ProdutoObrigatorio {
            get {
                return ResourceManager.GetString("ProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se informar a quantidade do produto superior a zero.
        /// </summary>
        public static string QuantidadeDoProdutoDeveSerSuperiorAZero {
            get {
                return ResourceManager.GetString("QuantidadeDoProdutoDeveSerSuperiorAZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A situação informada para o pedido é inválida.
        /// </summary>
        public static string SituacaoPedidoInvalida {
            get {
                return ResourceManager.GetString("SituacaoPedidoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui permissão para executar essa ação.
        /// </summary>
        public static string UsuarioSemPermissao {
            get {
                return ResourceManager.GetString("UsuarioSemPermissao", resourceCulture);
            }
        }
    }
}
